
development:
  adapter: postgresql
  encoding: utf8
  database: product
  pool: 5
  host: localhost
  username: postgres
  password: 2000

test:
  adapter: postgresql
  encoding: unicode
  database: product_test
  pool: 5
  username: postgres
  password: 2000


staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 
